from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

def generate_pdf(filename, data):
    """
    Generate PDF report from analysis record
    """

    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()

    content = []

    # Title
    content.append(Paragraph("Analysis Report", styles["Title"]))
    content.append(Spacer(1, 20))

    # Data fields
    content.append(Paragraph(f"ID: {data.get('id', '')}", styles["Normal"]))
    content.append(Paragraph(f"Input Type: {data.get('input_type', '')}", styles["Normal"]))
    content.append(Paragraph(f"Content: {data.get('content', '')}", styles["Normal"]))
    content.append(Paragraph(f"Risk Level: {data.get('risk_level', '')}", styles["Normal"]))
    content.append(Paragraph(f"Hash: {data.get('hash_value', '')}", styles["Normal"]))
    content.append(Paragraph(f"Created At: {data.get('created_at', '')}", styles["Normal"]))

    content.append(Spacer(1, 20))
    content.append(Paragraph("Generated by AI Security System", styles["Italic"]))

    doc.build(content)